[package]
name = "cli_compress"
version = "0.1.0"
edition = "2021"

[dependencies]
async_zip = { git = "https://github.com/Majored/rs-async-zip" } 
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.53"
