[package]
name = "async_zip"
version = "0.0.2"
edition = "2018"
authors = ["Harry [hello@majored.pw]"]
repository = "https://github.com/Majored/rs-async-zip"
description = "An asynchronous ZIP archive reading/writing crate with a heavy focus on streaming support."
readme = "README.md"
license = "MIT"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-compression = { version = "0.3.8", features = ["tokio", "deflate", "bzip2", "lzma", "zstd", "xz"]}
tokio = { version = "1.4.0", features = ["full"] }
chrono = "0.4.19"
crc32fast = "1.2.1"